### ISSUE TITLE
Improve styling of OJS's date input in quarto

### ISSUE THREAD

**Issue by scottfranz** [quarto-dev/quarto-cli#2863]
### Bug description

```{ojs}
viewof date = Inputs.date()
```
returns a "TypeError: Inputs.date is not a function"

I am using the Visual Studio Code Extension.

### Checklist

- [x] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [x] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [x] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [ ] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
It's likely that the date object is a recent extension to ObservableHQ and we don't track their stdlib on a day-to-day basis.

**Comment by scottfranz** [comment]
That makes sense. That's alright I was just letting y'all know. I was able to just import this [date input](https://observablehq.com/@jashkenas/inputs#dateDemo) for my project. Thanks!

**Comment by cscheid** [comment]
This now works on v1.3 prereleases, although the styling leaves a lot to be desired. I'm going to turn it into an enhancement.
