### ISSUE TITLE
Computation table output in margin errors for pdf rendering

### ISSUE THREAD

**Issue by cderv** [quarto-dev/quarto-cli#10112]
````markdown
---
title: "Table in margin"
format: pdf
keep-md: true
---

```{r}
#| column: margin
knitr::kable(head(mtcars[,1:2], 5))
```

````

this gives us 
````
compilation failed- error
LaTeX Error: Not in outer par mode.
````

* It fails also with latest 1.4
* It works with previous 1.3 

So this is a regression. 

Intermediate .md is 
````markdown
::: {.cell .column-margin}

```{.r .cell-code}
knitr::kable(head(mtcars[,1:2], 5))
```

::: {.cell-output-display}


|                  |  mpg| cyl|
|:-----------------|----:|---:|
|Mazda RX4         | 21.0|   6|
|Mazda RX4 Wag     | 21.0|   6|
|Datsun 710        | 22.8|   4|
|Hornet 4 Drive    | 21.4|   6|
|Hornet Sportabout | 18.7|   8|


:::
:::
````

Note that using `.column-margin` feature without computation seems ok 

````markdown
---
format: pdf
---

See table in margin

:::{.column-margin}

|                  |  mpg|
|:-----------------|----:|
|Mazda RX4         | 21.0|
|Mazda RX4 Wag     | 21.0|
|Datsun 710        | 22.8|
|Hornet 4 Drive    | 21.4|
|Hornet Sportabout | 18.7|

:::
````

So it seems to be a regression somewhere in 1.4 over 1.3

**Comment by cderv** [comment]
Working Latex 

````latex
\marginnote{\begin{footnotesize}

\begin{longtable}[]{@{}lr@{}}
\toprule\noalign{}
& mpg \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mazda RX4 & 21.0 \\
Mazda RX4 Wag & 21.0 \\
Datsun 710 & 22.8 \\
Hornet 4 Drive & 21.4 \\
Hornet Sportabout & 18.7 \\
\end{longtable}
````

In the document that fails 
````latex
\marginnote{\begin{footnotesize}

\begin{margintable}

\begin{longtable}[]{@{}lrr@{}}
\toprule\noalign{}
& mpg & cyl \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Mazda RX4 & 21.0 & 6 \\
Mazda RX4 Wag & 21.0 & 6 \\
Datsun 710 & 22.8 & 4 \\
Hornet 4 Drive & 21.4 & 6 \\
Hornet Sportabout & 18.7 & 8 \\
\end{longtable}

\end{margintable}%
````

it seems we using `margintable` in addition to what we used to do.

**Comment by cderv** [comment]
Possibly related to 
- https://github.com/quarto-dev/quarto-cli/issues/8772

but without crossref here

**Comment by cderv** [comment]
The commit that broke this is 6219f33489667b9b4857fb80ad58f70c5e7eaf82 

It is quite old: included first [v1.4.391](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.391)

We probably did not had test for the syntax.
