### ISSUE TITLE
Subtables fail to compile in beamer format

### ISSUE THREAD

**Issue by sun123zxy** [quarto-dev/quarto-cli#13372]
### I have:

- [x] searched the issue tracker for similar issues
- [x] installed the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
- [x] formatted my issue following the [Bug Reports guide](https://quarto.org/bug-reports.html)

### Bug description

This minimal example won't compile any more when I upgrade Quarto from v1.7.34 to v1.8.24:

`````qmd
---
title: Tables
format:
  beamer: default
---

### Tables

::: {#tbl-panel layout-ncol=2}
| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: First Table {#tbl-first}

| Col1 | Col2 | Col3 |
|------|------|------|
| A    | B    | C    |
| E    | F    | G    |
| A    | G    | G    |

: Second Table {#tbl-second}

Main Caption
:::
`````

Error report:

```bash
ERROR: 
compilation failed- error
Package subcaption Error: \subcaption outside float.

See the subcaption package documentation for explanation.
````

Suspect that this is due to #12775. Above file produces LaTeX code:

```latex
\begin{frame}{Tables}
\phantomsection\label{tables}
\begin{columns}[T]
\begin{column}{0.5\linewidth}
\subcaption{\label{tbl-first}First Table}

\centering{

\begin{tabular}{lll}
\toprule
Col1 & Col2 & Col3\\
\midrule
A & B & C\\
E & F & G\\
A & G & G\\
\bottomrule
\end{tabular}

}
\end{column}

\begin{column}{0.5\linewidth}
\subcaption{\label{tbl-second}Second Table}

\centering{

\begin{tabular}{lll}
\toprule
Col1 & Col2 & Col3\\
\midrule
A & B & C\\
E & F & G\\
A & G & G\\
\bottomrule
\end{tabular}

}
\end{column}
\end{columns}
\end{frame}
```

### Quarto check output

```bash
Quarto 1.8.24
[>] Checking environment information...
      Quarto cache location: C:\Users\sun123zxy\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.87.0: OK
      Deno version 2.3.1: OK
      Typst version 0.13.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.8.24
      Path: C:\Program Files\Quarto\bin
      CodePage: 936

[>] Checking tools....................OK
      TinyTeX: v2025.04
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\sun123zxy\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2025

[>] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: C:\Program Files\Google\Chrome\Application\chrome.exe
      Source: Windows Registry

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

      Unable to locate an installed version of R.
      Install R from https://cloud.r-project.org/


```

**Comment by sun123zxy** [comment]
As an additional test case, note that computational subtables also fail to compile:

`````qmd
---
title: "Test"
format:
  beamer: default
---

```{python}
#| label: fig-figure
#| fig-cap: figure
#| fig-subcap:
#|   - f1
#|   - f2
#| layout-ncol: 2

import matplotlib.pyplot as plt

fig, ax = plt.subplots()
plt.show()
fig, ax = plt.subplots()
plt.show()
```
`````

(produced Quarto 1.8.26)

**Comment by sun123zxy** [comment]
Ah, I tried subfigures and they also fail to compile:

`````qmd
---
title: "Test"
format: beamer
---

::: {#fig-elephants layout-ncol=2}

![Surus](surus.png){#fig-surus}

![Hanno](hanno.png){#fig-hanno}

Famous Elephants
:::
`````

All of them can be reproduced as of Quarto 1.8.27. It appears to be of some severity, will it be fixed?
