### PR TITLE
Lua,latex,table - fix code cells with `column: margin` and non-float tables

### LINKED ISSUE #10112: Computation table output in margin errors for pdf rendering
````markdown
---
title: "Table in margin"
format: pdf
keep-md: true
---

```{r}
#| column: margin
knitr::kable(head(mtcars[,1:2], 5))
```

````

this gives us 
````
compilation failed- error
LaTeX Error: Not in outer par mode.
````

* It fails also with latest 1.4
* It works with previous 1.3 

So this is a regression. 

Intermediate .md is 
````markdown
::: {.cell .column-margin}

```{.r .cell-code}
knitr::kable(head(mtcars[,1:2], 5))
```

::: {.cell-output-display}


|                  |  mpg| cyl|
|:-----------------|----:|---:|
|Mazda RX4         | 21.0|   6|
|Mazda RX4 Wag     | 21.0|   6|
|Datsun 710        | 22.8|   4|
|Hornet 4 Drive    | 21.4|   6|
|Hornet Sportabout | 18.7|   8|


:::
:::
````

Note that using `.column-margin` feature without computation seems ok 

````markdown
---
format: pdf
---

See table in margin

:::{.column-margin}

|                  |  mpg|
|:-----------------|----:|
|Mazda RX4         | 21.0|
|Mazda RX4 Wag     | 21.0|
|Datsun 710        | 22.8|
|Hornet 4 Drive    | 21.4|
|Hornet Sportabout | 18.7|

:::
````

So it seems to be a regression somewhere in 1.4 over 1.3

### PR DESCRIPTION
**Pull request by cscheid**
Closes #10112.

### CODE REVIEW

**Comment by cderv** [comment]
Thanks ! Do we backport to 1.4  as it was a 1.4 regression over 1.3 ? Or no more backport as 1.5 is soon to be out ?

**Comment by cscheid** [comment]
It's really a matter of effort/reward. Ideally, we'd do it, but I'd rather spend my time this week on getting 1.5 ready.

**Comment by cderv** [comment]
Yeah understood. It is just that we have some new commits into 1.4 already it seems. So probably a last patch will be done at some point, and so it would be worth adding this known one. 

but indeed some effort, and maybe we won't patch v1.4 anymore once 1.5 is out. There would be no strong advantage to do it, once last stable become 1.5. 

So we are in the middle, and I am trying to not forget anything :) 

Let's go for 1.5 !
