### ISSUE TITLE
Won't build with Deno >=1.29 

### ISSUE THREAD

**Issue by trap000d** [quarto-dev/quarto-cli#4212]
### Bug description

Environment: Arch Linux
Deno: 1.30.1
RStudio vesion: irrelevant
AUR Package: quarto-cli-pre-release (I'm maintainer)

Since 1.29 Deno has dropped some API calls, in particular, `Deno.spawnSync`. As result the following error has thrown when I'm trying to build `quarto-cli-pre-release`:

```
Creating Deno Bundle
/var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/package/dist/bin/quarto.js
Check file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/src/quarto.ts
error: TS2339 [ERROR]: Property 'spawnSync' does not exist on type 'typeof Deno'.
  Deno.spawnSync;
       ~~~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/src/vendor/deno.land/std@0.166.0/node/process.ts:63:8

TS2367 [ERROR]: This comparison appears to be unintentional because the types 'rmdirOptions | undefined' and 'boolean' have no overlap.
    if (options === false) {
        ~~~~~~~~~~~~~~~~~
    at file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/src/vendor/deno.land/std@0.166.0/node/_fs/_fs_rmdir.ts:88:9

Found 2 errors.
ERROR: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/src/quarto.ts

Error: Failure to bundle /var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/src/quarto.ts
    at bundle (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/package/src/util/deno.ts:40:11)
    at async prepareDist (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/package/src/common/prepare-dist.ts:39:3)
    at async Command.fn (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/package/src/cmd/pkg-cmd.ts:38:5)
    at async Command.execute (https://deno.land/x/cliffy@v0.25.4/command/command.ts:1790:7)
    at async quartoBld (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/package/src/bld.ts:48:3)
    at async mainRunner (file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/src/core/main.ts:39:5)
    at async file:///var/tmp/makepkg/quarto-cli-pre-release/src/quarto-cli-1.3.154/package/src/bld.ts:52:3
==> ERROR: A failure occurred in build().
    Aborting...

```

I hope upgrade of https://github.com/quarto-dev/quarto-cli/tree/main/src/vendor/deno.land/std%400.166.0 to the most recent version (https://github.com/denoland/deno_std/releases/tag/0.176.0) might resolve the issue.... 

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by jgenco** [comment]
I had luck upgrading deno_std to 0.170.0 and deno-cliffy to 0.25.7 for Deno 1.29.4

**Comment by cscheid** [comment]
Deno's API doesn't try to be backwards compatible and moves faster than our release schedule. Unfortunately, that means that we can only ensure each release works with the version of deno that we advertise on https://github.com/quarto-dev/quarto-cli/blob/main/configuration#L11.

We will update the deno version prior to this release, but this sort of issue will continue happening. We do keep up on a per-release basis, but to be clear, we don't consider this to be a bug.

**Comment by trap000d** [comment]
> I had luck upgrading deno_std to 0.170.0 and deno-cliffy to 0.25.7 for Deno 1.29.4

Yay, that works. Here my ugly patch: https://github.com/trap000d/aur/tree/master/quarto-cli-pre-release

**Comment by jgenco** [comment]
deno cache --unstable --lock ./src/resources/deno_std/deno_std.lock  --lock-write ./package/scripts/deno_std/deno_std.ts 

see [lock.sh](https://github.com/quarto-dev/quarto-cli/blob/e57a199361b0df8494e639b96ede2b34c5492059/package/scripts/deno_std/lock.sh) and [download.sh](https://github.com/quarto-dev/quarto-cli/blob/e57a199361b0df8494e639b96ede2b34c5492059/package/scripts/deno_std/download.sh)

**Comment by cscheid** [comment]
@trap000d @jgenco It's a little more complicated than that in our case, because we create a full copy of the necessary deno libraries in a vendor directory. The process is a little complicated; I think you'll need to follow along the behavior of https://github.com/quarto-dev/quarto-cli/blob/main/configure.sh to get everything working the same way.
