### PR TITLE
[backport] Fix dart-sass failure on Windows usernames containing ampersand

### LINKED ISSUE #14534: Quarto render fails when Windows username contains ampersand
### I have:

- [x] searched the issue tracker for similar issues
- [x] installed the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
- [x] formatted my issue following the [Bug Reports guide](https://quarto.org/bug-reports.html)

### Bug description

Originally reported via RStudio, but have confirmed it is a Quarto issue (happens from terminal, outside RStudio, with a trivial example). Details in https://github.com/rstudio/rstudio/issues/17712.

In short, when using Quarto via a Windows user account that has an ampersand in the username, rendering will not work. This worked with Quarto 1.8, but fails with 1.9.

There's a related bug that happens with both 1.8 and 1.9 if you install Quarto per-user with this `gary&ritchie` style username, Quarto fails with a different error message (didn't capture it). Installing for all users (i.e. outside the troublesome path) avoids this problem.

### Steps to reproduce

- Create a Windows user account that has an ampersand, e.g. `C:\Users\gary&ritchie\` and login as that user
- With Quarto 1.9.37, and a trivial Quarto doc (I used whatever RStudio creates for a new Quarto doc project) somewhere in the user's profile (e.g. `C:\Users\gary&ritchie\Documents\bug-repro\bug-repro.qmd`) try to render using the same command-line that RStudio uses

Here's a transcript showing this failing with 1.9, and working with 1.8:
```
C:\Users\gary&ritchie\Documents\bug-repro>quarto --version
1.9.37

C:\Users\gary&ritchie\Documents\bug-repro>quarto preview bug-repro.qmd --to default --no-watch-inputs --no-browse


processing file: bug-repro.qmd
1/3
2/3 [unnamed-chunk-1]
3/3
output file: bug-repro.knit.md

ERROR: Theme file compilation failed:

'C:\Users\GARY' is not recognized as an internal or external command,
operable program or batch file.

Stack trace:
    at processResult (file:///C:/Program Files/Quarto/bin/quarto.js:79152:13)
    at dartCommand (file:///C:/Program Files/Quarto/bin/quarto.js:79169:12)
    at eventLoopTick (ext:core/01_core.js:179:7)
    at async dartCompile (file:///C:/Program Files/Quarto/bin/quarto.js:79120:3)
    at async file:///C:/Program Files/Quarto/bin/quarto.js:87618:9
    at async SassCache.setFromHash (file:///C:/Program Files/Quarto/bin/quarto.js:80054:11)
    at async compileSass (file:///C:/Program Files/Quarto/bin/quarto.js:87429:19)
    at async resolveSassBundles (file:///C:/Program Files/Quarto/bin/quarto.js:125158:17)
    at async resolveExtras (file:///C:/Program Files/Quarto/bin/quarto.js:129822:14)
    at async runPandoc (file:///C:/Program Files/Quarto/bin/quarto.js:129246:20)


-- downgrade to 1.8.27, problem goes away --

C:\Users\gary&ritchie\Documents\bug-repro>quarto --version
1.8.27

C:\Users\gary&ritchie\Documents\bug-repro>quarto preview bug-repro.qmd --to default --no-watch-inputs --no-browse


processing file: bug-repro.qmd
1/3
2/3 [unnamed-chunk-1]
3/3
output file: bug-repro.knit.md

pandoc
  to: html
  output-file: bug-repro.html
  standalone: true
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  variables: {}

metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  editor: visual
  title: bug-repro

Output created: bug-repro.html

Watching files for changes
Browse at http://localhost:4691/bug-repro.html
Listening on http://127.0.0.1:4691/

```

### Actual behavior

- With Quarto 1.8.25 and 1.8.27, this works (RStudio 2026.01 bundled 1.8).
- With Quarto 1.9.37 it fails with `'C:\Users\GARY' is not recognized as an internal or external command,
operable program or batch file.` (RStudio 2026.05 bundled 1.9)

### Expected behavior

Everything works despite the ampersand in the user profile name.

Ideally, installing Quarto per-user with such a name should also work, but probably a separate issue.

### Your environment

Windows-11 Pro, x64

### Quarto check output

I installed Quarto standalone via the MSI installer, using 1.8.27 and 1.9.37.

### PR DESCRIPTION
**Pull request by cderv**
> [!IMPORTANT]
> Backport from #14273

When the Windows user profile path contains `&` (e.g., `C:\Users\Tom & Jerry\`), `quarto render` of any document with sass fails with `'C:\Users\Tom' is not recognized as an internal or external command`. The ampersand is a `cmd.exe` command separator, so the temp `.bat` wrapper that `safeWindowsExec` writes is split mid-path and the second half is interpreted as a separate command.

## Root Cause

v1.9 introduced `safeWindowsExec` to handle spaced paths (#13997), which writes a temp `.bat` and runs it through `cmd.exe /c`. Any `&` in the program path lets `cmd.exe` split the line. The existing #14367 fallback to direct `sass.bat` execution does not help — Windows still spawns `cmd.exe` internally to interpret any `.bat`, and the ampersand splits again there.

## Fix

Backport of the `dart.exe` + `sass.snapshot` direct-invocation rewrite from #14273. Calling `dart.exe` via `Deno.Command` bypasses `cmd.exe` entirely, removing the whole class of `.bat`-related issues on Windows (ampersand splitting, OEM/UTF-8 code page mismatch, enterprise group policy blocks).

The bundled dart-sass version is identical between v1.9 and main (`DARTSASS=1.87.0`), so the `src/dart.exe` + `src/sass.snapshot` layout assumed by the fix is the same on disk in v1.9.

This subsumes the #14367 fallback approach (no `.bat` = no policy block) and reinforces the #14267 accented-path fix already backported via #14274.

Out of scope: other `safeWindowsExec` callers (`texlive.ts`, `zip.ts`, `shell.ts`) still go through `cmd.exe` and remain vulnerable to `&` in paths. Those have separate upstream fixes and are not covered by this backport.

## Test Plan

- [x] Render a document with sass on Windows where the user profile path contains `&`
- [x] Render a document with sass on Windows with a normal user profile (no regression)
- [x] Render a document with sass on macOS/Linux (non-Windows path unchanged)
- [x] Render a document with `QUARTO_DART_SASS` env override pointing to a custom `sass.exe`
- [x] `unit/dart-sass.test.ts` and `unit/windows-exec.test.ts` pass on Windows CI

Fixes #14534

### CODE REVIEW

**Comment by cderv** [comment]
@cscheid I am thinking of backporting this fix that I initially did not backport because it was bigger change that I would expect for a backport. 

However it impacts RStudio users (#14534) for which quarto was working in v1.8 and no more in v1.8. It was reported in our repo from a report on RStudio IDE by @gtritchie. 

It is scoped to Windows user only, and should not create problem because it is improvement but... 🤷‍♂️ you never know. 

What do you think ? This is so next RStudio IDE could maybe bundle a patch v1.9 before we do release a stable v1.10. @gtritchie if we do a patch release with such fix, is there greater probability to have a v1.9 patch bundled into next RStudio IDE ? 

Anyhow, this would be available for user to download stable themself. 

@cscheid I just prefered to have your go on this before merging. (Reminder: the fix is already in v1.10.3 following #14273)

**Comment by cscheid** [comment]
I think a backport is ideal here, assuming everything goes smoothly.

But I _also_ think that using `&` in a username is, um, ill-advised. If it turns out that this fix is bad for other reasons, we should feel ok with reverting it and choosing not to fix.

File: src/core/dart-sass.ts [hunk 1]
```diff
@@ -1,20 +1,18 @@
 /*
  * dart-sass.ts
  *
- * Copyright (C) 2020-2022 Posit Software, PBC
+ * Copyright (C) 2020-2025 Posit Software, PBC
```
Comment (cscheid) [inline src/core/dart-sass.ts]: If we're going to fix this, it's 2026 :D

**Review by cscheid — APPROVED** [review]

**Comment by gtritchie** [comment]
The upcoming release of RStudio (2026.05) is already locked and loaded, we can't take changes for anything unless incredibly serious. Handling ampersands in usernames would not meet the bar, IMO.

Having a patched 1.9 would be _nice_ since we could tell impacted users to install that separately, without having to downgrade to 1.8.

We are doing monthly releases of RStudio now, and I could incorporate this into 2026.06 if available in the next few weeks.

File: src/core/dart-sass.ts (hunk 1 above)
Comment (gtritchie) [reply src/core/dart-sass.ts]: Took me a long time to convince Claude Code that it was 2026. I don't think it believed me.

Comment (cderv) [reply src/core/dart-sass.ts]:
```suggestion
 * Copyright (C) 2020-2026 Posit Software, PBC
```

**Comment by cderv** [comment]
Thanks ! I'll merge this and include in next patch release. 

This way you can consider it for next RStudio IDE - the patch will have other fix worth having in a new IDE release I think.
