### ISSUE TITLE
Theme file compilation failed on corporate Windows machines with AppLocker/GPO after upgrade to 1.9.36

### ISSUE THREAD

**Issue by ThomasFaria** [quarto-dev/quarto-cli#14423]
### I have:

- [x] searched the issue tracker for similar issues
- [x] installed the latest version of [Quarto CLI](https://github.com/quarto-dev/quarto-cli/releases/latest)
- [x] formatted my issue following the [Bug Reports guide](https://quarto.org/bug-reports.html)

### Bug description

Since upgrading from Quarto 1.8.x to 1.9.36, rendering any Quarto HTML document fails with ERROR: Theme file compilation failed. The project rendered correctly on the exact same machine (corporate) under 1.8.x.

### Steps to reproduce

```
---
lang: fr
format:
  html: default
---

# Test 

```

### Actual behavior

It appears that starting with 1.9.36, Quarto no longer invokes dart-sass directly, but instead wraps the call inside a dynamically generated batch file placed in %TEMP% (e.g. quarto-safe-exec***.bat), and then executes it via cmd /c.
On corporate machines governed by AppLocker (which is my case), execution of arbitrary scripts from %TEMP% is typically blocked by policy. This was not an issue under 1.8.x, suggesting the intermediate batch file wrapper is a behavioral change introduced in 1.9.x. but I did'nt manage to find it in the release notes.

```
PS C:\Users\tfaria\Documents\Projets\veille-bloom> quarto render '.\veille copy.qmd' --log-level debug
Quarto version: 1.9.36
Loaded deno-dom-native
Creating SassCache at C:\Users\tfaria\Documents\Projets\veille-bloom\.quarto\quarto-session-temp5ca40997ae5fd509\sass
Returning SassCache at C:\Users\tfaria\Documents\Projets\veille-bloom\.quarto\quarto-session-temp5ca40997ae5fd509\sass
SassCache.getOrSet(...)
SassCache.getFromHash(hash=c254a1cd427ccee204209ecc0058546b, inputHash=40c995d5a6019965451b2dcd102fbdaa, force=undefined)
  cache miss
  cache miss, setting
SassCache.setFromHash(c254a1cd427ccee204209ecc0058546b, 40c995d5a6019965451b2dcd102fbdaa), ...
[execProcess] cmd /c C:\Users\tfaria\AppData\Local\Temp\quarto-safe-exece4e2f3c181a32514.bat
[execProcess] Success: false, code: 1
[DART path]   : C:\Program Files\Quarto\bin\tools\x86_64\dart-sass\sass.bat
[DART args]   : C:\Users\tfaria\Documents\Projets\veille-bloom\.quarto\quarto-session-temp5ca40997ae5fd509\7b4a723208381367.scss C:\Users\tfaria\Documents\Projets\veille-bloom\.quarto\quarto-session-temp5ca40997ae5fd509\sass\c254a1cd427ccee204209ecc0058546b.css --style compressed --quiet --load-path=C:\Program Files\Quarto\share\formats\html\bootstrap\dist\scss --load-path=C:\Program Files\Quarto\share\formats\html\bslib\bslib-scss
[DART stdout] : 
[DART stderr] : **Ce programme est bloqu� par une strat�gie de groupe. Pour plus d'informations, contactez votre administrateur syst�me.**

SassCache cleanup executing for C:\Users\tfaria\Documents\Projets\veille-bloom\.quarto\quarto-session-temp5ca40997ae5fd509\sass
[NotebookContext]: Starting Cleanup
ERROR: Theme file compilation failed:



Stack trace:
    at processResult (file:///C:/Program Files/Quarto/bin/quarto.js:79072:13)
    at dartCommand (file:///C:/Program Files/Quarto/bin/quarto.js:79089:12)
    at eventLoopTick (ext:core/01_core.js:179:7)
    at async dartCompile (file:///C:/Program Files/Quarto/bin/quarto.js:79040:3)
    at async file:///C:/Program Files/Quarto/bin/quarto.js:87538:9
    at async SassCache.setFromHash (file:///C:/Program Files/Quarto/bin/quarto.js:79974:11)
    at async compileSass (file:///C:/Program Files/Quarto/bin/quarto.js:87349:19)
    at async resolveSassBundles (file:///C:/Program Files/Quarto/bin/quarto.js:125076:17)
    at async resolveExtras (file:///C:/Program Files/Quarto/bin/quarto.js:129740:14)
    at async runPandoc (file:///C:/Program Files/Quarto/bin/quarto.js:129164:20)
```

### Expected behavior

Produce an HTML file

### Your environment

OS: Windows 11, **corporate-managed (Group Policy / AppLocker enforced)**
``

### Quarto check output

So same problem for quarto check...
```


quarto check --log-level debug
Quarto version: 1.9.36
Quarto 1.9.36
[>] Checking environment information...
      Quarto cache location: C:\Users\tfaria\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
[execProcess] C:\Program Files\Quarto\bin\tools\pandoc --version
[execProcess] Success: true, code: 0
[execProcess] cmd /c C:\Users\tfaria\AppData\Local\Temp\quarto-safe-exec21fe9269d91c6144.bat
[execProcess] Success: false, code: 1
[DART path]   : C:\Program Files\Quarto\bin\tools\x86_64\dart-sass\sass.bat
[DART args]   : --version
[DART stdout] : 
[DART stderr] : Ce programme est bloqu� par une strat�gie de groupe. Pour plus d'informations, contactez votre administrateur syst�me.

[NotebookContext]: Starting Cleanup
ERROR: Theme file compilation failed:



Stack trace:
    at processResult (file:///C:/Program Files/Quarto/bin/quarto.js:79072:13)
    at dartCommand (file:///C:/Program Files/Quarto/bin/quarto.js:79089:12)
    at eventLoopTick (ext:core/01_core.js:179:7)
    at async checkVersions (file:///C:/Program Files/Quarto/bin/quarto.js:163474:24)
    at async check (file:///C:/Program Files/Quarto/bin/quarto.js:163388:9)
    at async _Command.actionHandler (file:///C:/Program Files/Quarto/bin/quarto.js:163784:3)
    at async _Command.execute (file:///C:/Program Files/Quarto/bin/quarto.js:102022:7)
    at async _Command.parseCommand (file:///C:/Program Files/Quarto/bin/quarto.js:101899:14)
    at async quarto4 (file:///C:/Program Files/Quarto/bin/quarto.js:187547:5)
    at async file:///C:/Program Files/Quarto/bin/quarto.js:187575:5
```

**Comment by mcanouil** [comment]
This seems to be a duplicate of:

- https://github.com/quarto-dev/quarto-cli/issues/14367

**Comment by ThomasFaria** [comment]
Arf, you are right ! Sorry for that ! I close it then

**Comment by mcanouil** [comment]
@ThomasFaria you'll have to wait for 1.9.38 patch release.
