### PR TITLE
Fix axe accessibility checks for revealjs and dashboard formats

### LINKED ISSUE #13781: Bug in axe accessibility checks for revealjs formats
### Description

Quarto >1.8 has integrated support for `axe-core` accessibility checking html. The docs say that the axe YAML metadata configuration can be added to HTML formats (`html`, `dashboard`, and `revealjs`).

However, adding axe to the yaml for the `revealjs` format results in an error in compiling the sass themes. The error is:
```{bash}
ERROR: Theme file compilation failed:

Error: Undefined variable.
   ╷
67 │   border: 1px solid $body-color;
```

Line 67 defining the border is in `quarto.js` This suggests that theme file sass compilation is occurring *after* quarto.js inclusion, though it needs to happen *before.*

Accessibility enhancements should be high-priority due to [new rules taking effect in April 2026 under Title II of the Americans with Disabilities Act](https://agb.org/news/agb-alerts/agb-policy-alert-ada-digital-accessibility-rule-requires-full-compliance-by-april-2026/) and the requirements of the [European Accessibility Act (EAA), which went into effect in June 2025](https://commission.europa.eu/strategy-and-policy/policies/justice-and-fundamental-rights/disability/union-equality-strategy-rights-persons-disabilities-2021-2030/european-accessibility-act_en). Many users are now liable for the documents they render meeting these requirements.

Related discussion items:

* [Ensure Quarto Meets WCAG 2.1 AA Standards #12644](https://github.com/orgs/quarto-dev/discussions/12644)
* [Increase options/guidance for compliance with Web Content Accessibility Guidelines (WCAG) in revealjs HTML output #8621](https://github.com/orgs/quarto-dev/discussions/8621)
* [https://github.com/orgs/quarto-dev/discussions/11847](https://github.com/orgs/quarto-dev/discussions/11847)

**Minimal (not) working example. Change format to "html" to create something that renders appropriately.**

````{md}
---
title: "Axe Causes Sass Compilation Error"
date: today
format: 
  revealjs:
    axe: true
---

## Axe test.

This violates contrast rules: [insufficient contrast.]{style="color: #eee"}.

This test works with the format as `html` but not with the format as `revealjs`.

## For revealjs, axe causes theme file compilations to fail.

The resulting error is:

```{bash}
ERROR: Theme file compilation failed:

Error: Undefined variable.
   ╷
67 │   border: 1px solid $body-color;
```

Line 67 defining the border is in `quarto.js`

This suggests that theme file sass compilation is occurring after quarto.js inclusion, though it needs to happen before.

## The end

Bug found in Quarto 1.8.26 on 10 December 2025
````

_Originally posted by @paytonej in https://github.com/quarto-dev/quarto-cli/discussions/13780_

### PR DESCRIPTION
**Pull request by cderv**
Adding `axe: true` to revealjs format fails with SCSS compilation error (`Undefined variable: $body-color`). Additionally, axe checks never run for revealjs or dashboard formats even when the SCSS issue is worked around.

## Root Cause

Two issues in the original axe implementation (#12730):

1. `axe-check.js` was imported by `quarto.js`, which only loads for bootstrap-based HTML. RevealJS and dashboard formats never load `quarto.js`, so axe never initializes.

2. Axe SCSS uses Bootstrap variables (`$body-color`, `$body-bg`) that don't exist in the revealjs Sass compilation context, which compiles separately from the theme.

### Phase 1: Test coverage (TDD)

Wrote comprehensive tests first to confirm the broken state. All axe output modes (console, json, document) tested across html, revealjs, and dashboard. HTML passed; revealjs and dashboard failed as expected.

### Phase 2: Core loading fix

Decoupled axe from the bootstrap pipeline:

- Removed `axe-check.js` import from `quarto.js`
- Added self-initialization to `axe-check.js` (runs when loaded as module)
- Added `FormatDependency` in `format-html-axe.ts` to load `axe-check.js` as `type="module"` when axe config is present
- Added `!default` SCSS fallback values with CSS custom property bridge (`var(--r-main-color, $body-color)`) for cross-format theming

This fixed axe loading for all formats, but revealed that the document reporter assumes a `<main>` element exists — which neither revealjs nor dashboard have.

### Phase 3: Format-specific report placement

Rather than a simple DOM fallback, each format got appropriate UX:

- **RevealJS:** Report as a dedicated slide appended to the deck. Hover-to-highlight uses `Reveal.slide()` to navigate to the offending slide. All slides (including hidden ones) are temporarily unhidden for scanning since RevealJS sets `hidden`/`aria-hidden` on non-visible slides.
- **Dashboard:** Bootstrap offcanvas sidebar (`backdrop: false`, `scroll: true`) so content stays interactive. Floating toggle button to open/close. Automatically rescans when switching pages, card tabsets, or toggling the sidebar — dashboard hides inactive content with `display: none`, making axe results stale on navigation.
- **HTML:** Fixed overlay (unchanged from original).

### Phase 4: Hardening and cleanup

From code review: wrapped `init()` in try/catch/finally so `data-quarto-axe-complete` is always set (prevents Playwright hangs on CDN failure), fixed nodeElement creation inside the violation nodes loop (was sharing one div across all nodes), normalized `axe: true` to `{output: "console"}` at construction time.

Refactored axe options injection to use `FormatDependency` head field instead of temp file + `kIncludeInHeader`, leveraging the existing dependency system.

## Test Coverage

- 431-line Playwright test (`axe-accessibility.spec.ts`): all output modes across html, revealjs (light/dark/vertical slides), and dashboard (multi-page, card tabsets)
- 5 smoke-all tests for conditional inclusion and explicit disable
- Cross-slide scanning, completion signal, rescan on navigation, dark theme CSS bridge

Fixes #13781

### CODE REVIEW

**Comment by cderv** [comment]
Filled test coverage gaps from review feedback (beads `quarto-cli-3eje.5`):

- Dashboard console/json output modes
- Dashboard dark theme
- HTML hover interaction
- Negative tests for revealjs/dashboard (smoke-all)

Also updated hover tests to use `.first()` for non-unique selectors following Playwright best practices.

All tests passing: 75 Playwright (3 browsers), 9 smoke-all.
