### ISSUE TITLE
[version 1.4] Bibliography error

### ISSUE THREAD

**Issue by fredguth** [quarto-dev/quarto-cli#6938]
### Bug description

The following works with quarto 1.3.450

````
quarto use template fredguth/tufte-quarto
(go to folder)
quarto render
````
The same does not work with quarto 1.4.376

### Expected behavior

It should render a pdf file in the _docs folder.

### Actual behavior

```
**ERROR:
compilation failed- error
Package natbib Error: Bibliography not compatible with author-year citations.
(natbib)                Press <return> to continue in numerical citation style.

See the natbib package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.62 ...mand\NAT@force@numbers{}\NAT@force@numbers**

```

### Your environment

Mac OS

**Comment by mcanouil** [comment]
Could you use `keep-tex: true` and investigate the issue on your extension as it seems to be a conflict with some (new) default in Quarto?

**Comment by dragonstyle** [comment]
I think that perhaps the extension should be explicitly specifying the `cite-method` to be `natbib` (it's possible that the behavior changed in the pandoc template to check this more explicitly. When I try adding that to the `pdf` format key, I do get different behavior (though then it is complaining about a missing `dinat.bst` file).

I also had missing fonts on my system, so this version worked for me:

```
title: Tufte Quarto
author: Fred Guth
version: 1.1.0
quarto-version: ">=1.2.215"
contributes:
  project:
    project:
      type: book
      output-dir: docs
    format:
      html:
        page-layout: full
        reference-location: margin
        citation-location: block
        title-block-style: none
        css: styles.css
        number-sections: false
        linkcolor: Maroon
        backgroundcolor: FloralWhite
        sidebarbackgroundcolor: FloralWhite
        mainfont: "heuristica"
        toc-location: left
        toc-title: "Contents"
        default-image-extension: svg
      pdf:
        reference-location: margin
        citation-location: margin
        fig-cap-location: bottom
        documentclass: tufte-book
        classoption: [sfsidenotes]
        number-sections: false
        format-resources:
          - tufte-book.cls
          - tufte-common.def
          - tufte.bst
        template-partials: # replaces
          - "partials/title.tex"
          - "partials/before-body.tex"
        include-in-header: #adds
          - "partials/in-header.tex"
          - "partials/definitions.tex"
        include-after-body: #adds
          - "partials/after-body.tex"
        toc-depth: 2
        toc-title: "Contents"
        indent: 0px
        # biblio-style: dinat
        cite-method: natbib
        # mainfont: "Minion Pro"
        # mainfont: "ETbb"
        # sansfont: "TeX Gyre Heros"
        # sansfontoptions: "Scale=MatchUppercase"
        default-image-extension: pdf
  ```

**Comment by pat-alt** [comment]
Possibly related https://github.com/pat-alt/quarto-juliacon-proceedings/issues/28

I get the same error when specifying the `biblio-style` option both on `1.3.450` and the dev version.
