### ISSUE TITLE
Quarto does not work with python 3.6

### ISSUE THREAD

**Issue by zippeurfou** [quarto-dev/quarto-cli#4452]
### Bug description

If you have python 3.6.9 for example quarto will error with the error message:
```
module 'asyncio' has no attribute 'get_running_loop'
```
You can reproduce it by installing it in a virtual environment and executing `quarto check`:
```
$quarto check
[✓] Checking Quarto installation......OK
      Version: 1.2.335
      Path: /home/mferradou/opt/quarto-1.2.335/bin

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.6.9
      Path: /usr/bin/python3
      Jupyter: 4.6.3
      Kernels: python2, python3

(\) Checking Jupyter engine render....

module 'asyncio' has no attribute 'get_running_loop'
sys:1: RuntimeWarning: coroutine 'get_info' was never awaited
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
[✓] Checking Jupyter engine render....OK
```
This won't allow you to use the render function.
This was tested on ubuntu x86_64.

### Checklist

- [X] Please include a minimal, fully reproducible example in a single .qmd file? Please provide the whole file rather than the snippet you believe is causing the issue.
- [X] Please [format your issue](https://quarto.org/bug-reports.html#formatting-make-githubs-markdown-work-for-us) so it is easier for us to read the bug report.
- [X] Please document the RStudio IDE version you're running (if applicable), by providing the value displayed in the "About RStudio" main menu dialog?
- [X] Please document the operating system you're running. If on Linux, please provide the specific distribution.

**Comment by cscheid** [comment]
That's correct, we don't support Python 3.6; it's been [end-of-life'd](https://devguide.python.org/versions/) since 2021-12-23.
